# Generated by Django 2.2.2 on 2020-01-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile_link',
        ),
    ]
