# Generated by Django 2.2.2 on 2020-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_post_user_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_profile_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
