# Generated by Django 2.2.2 on 2020-01-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_post_user_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile_link',
        ),
    ]
